# Generated by Django 6.0.7 on 2026-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_nb_o_gender_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], db_index=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_active_match',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('M', 'Homens'), ('F', 'Mulheres'), ('A', 'Todos')], db_index=True, default='', max_length=1),
        ),
    ]
