# Generated by Django 6.0.7 on 2026-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_gender_alter_profile_has_active_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_age_preference',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_distance_km',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_age_preference',
            field=models.IntegerField(default=18),
        ),
    ]
