# Generated by Django 6.0.7 on 2026-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_children_profile_company_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_birth_date_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
