# Generated by Django 6.0.7 on 2026-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
